import { beforeEach, describe, expect, it, vi } from 'vitest';
import { App, TFile } from 'obsidian';
import { openAndroidPrintDocument } from '../src/utils/androidPrintDocument';

interface StoredFile {
    file: TFile;
    content: string;
}

function createFile(path: string): TFile {
    const extension = path.includes('.') ? path.split('.').pop() ?? '' : '';
    const filename = path.split('/').pop() ?? path;

    return Object.assign(new TFile(), {
        path,
        basename: extension ? filename.slice(0, -(extension.length + 1)) : filename,
        extension
    });
}

function createApp(initialFiles: Array<{ path: string; content: string }> = []) {
    const storedFiles = new Map<string, StoredFile>();

    initialFiles.forEach(({ path, content }) => {
        storedFiles.set(path, {
            file: createFile(path),
            content
        });
    });

    const app = {
        vault: {
            getAbstractFileByPath: vi.fn((path: string) => storedFiles.get(path)?.file ?? null),
            create: vi.fn(async (path: string, content: string) => {
                const file = createFile(path);
                storedFiles.set(path, { file, content });
                return file;
            }),
            cachedRead: vi.fn(async (file: TFile) => storedFiles.get(file.path)?.content ?? ''),
            process: vi.fn(async (file: TFile, update: (content: string) => string) => {
                const storedFile = storedFiles.get(file.path);
                if (!storedFile) {
                    throw new Error('File not found');
                }

                storedFile.content = update(storedFile.content);
                return storedFile.content;
            }),
            readBinary: vi.fn(async () => new Uint8Array([1, 2, 3]).buffer)
        },
        metadataCache: {
            getFirstLinkpathDest: vi.fn(() => null)
        },
        openWithDefaultApp: vi.fn(async () => undefined)
    };

    return {
        app: app as unknown as App & { openWithDefaultApp?: (path: string) => Promise<void> },
        storedFiles
    };
}

function getMockNotices(): string[] {
    const globalWithNoticeStore = globalThis as typeof globalThis & {
        __obsidianMockNotices?: string[];
    };

    if (!globalWithNoticeStore.__obsidianMockNotices) {
        globalWithNoticeStore.__obsidianMockNotices = [];
    }

    return globalWithNoticeStore.__obsidianMockNotices;
}

describe('openAndroidPrintDocument', () => {
    beforeEach(() => {
        vi.clearAllMocks();
        getMockNotices().length = 0;
    });

    it('creates and opens one marked standalone print document', async () => {
        const { app, storedFiles } = createApp();
        const content = document.createElement('div');
        content.textContent = 'Quarterly report';

        await openAndroidPrintDocument(
            app,
            'Report',
            content,
            'body { color: black; }',
            ['invoice']
        );

        const generatedContent = storedFiles.get('obsidian-print-output.html')?.content ?? '';
        expect(generatedContent).toContain('Generated by the Obsidian Print plugin');
        expect(generatedContent).toContain('<meta name="viewport" content="width=device-width, initial-scale=1">');
        expect(generatedContent).toContain('<title>Report</title>');
        expect(generatedContent).toContain('data:text/css;charset=utf-8,body%20%7B%20color%3A%20black%3B%20%7D');
        expect(generatedContent).toContain('Quarterly report');
        expect(generatedContent).toContain('invoice');
        expect(app.openWithDefaultApp).toHaveBeenCalledWith('obsidian-print-output.html');
    });

    it('reuses its marked output file on the next print', async () => {
        const { app, storedFiles } = createApp();

        await openAndroidPrintDocument(app, 'First', document.createElement('div'), '');

        const secondContent = document.createElement('div');
        secondContent.textContent = 'Second print';
        await openAndroidPrintDocument(app, 'Second', secondContent, '');

        expect(app.vault.create).toHaveBeenCalledOnce();
        expect(app.vault.process).toHaveBeenCalledOnce();
        expect(storedFiles.get('obsidian-print-output.html')?.content).toContain('Second print');
    });

    it('never overwrites an existing user file', async () => {
        const { app, storedFiles } = createApp([{
            path: 'obsidian-print-output.html',
            content: '<!DOCTYPE html><p>User content</p>'
        }]);

        await openAndroidPrintDocument(app, 'Print', document.createElement('div'), '');

        expect(storedFiles.get('obsidian-print-output.html')?.content).toContain('User content');
        expect(storedFiles.get('obsidian-print-output-2.html')?.content).toContain('Generated by the Obsidian Print plugin');
        expect(app.openWithDefaultApp).toHaveBeenCalledWith('obsidian-print-output-2.html');
    });

    it('embeds local vault images and keeps remote images unchanged', async () => {
        const { app, storedFiles } = createApp();
        const imageFile = createFile('notes/images/photo.png');
        const content = document.createElement('div');
        content.className = 'obsidian-print-note';
        content.setAttribute('data-obsidian-print-source-path', 'notes/report.md');
        content.innerHTML = `
            <span class="internal-embed" src="images/photo.png">
                <img src="capacitor://localhost/photo.png" srcset="capacitor://localhost/photo@2x.png 2x">
            </span>
            <img src="https://example.com/logo.png">
        `;

        app.metadataCache.getFirstLinkpathDest = vi.fn(() => imageFile);

        await openAndroidPrintDocument(app, 'Images', content, '');

        const generatedContent = storedFiles.get('obsidian-print-output.html')?.content ?? '';
        expect(generatedContent).toContain('src="data:image/png;base64,AQID"');
        expect(generatedContent).not.toContain('srcset=');
        expect(generatedContent).toContain('src="https://example.com/logo.png"');
        expect(app.vault.readBinary).toHaveBeenCalledWith(imageFile);
    });

    it('preserves canvas-rendered content in the standalone document', async () => {
        const { app, storedFiles } = createApp();
        const content = document.createElement('div');
        const canvas = document.createElement('canvas');

        Object.defineProperty(canvas, 'toDataURL', {
            value: vi.fn(() => 'data:image/png;base64,rendered-canvas')
        });
        content.appendChild(canvas);

        await openAndroidPrintDocument(app, 'Canvas', content, '');

        const generatedContent = storedFiles.get('obsidian-print-output.html')?.content ?? '';
        expect(generatedContent).toContain('src="data:image/png;base64,rendered-canvas"');
        expect(generatedContent).not.toContain('<canvas');
    });

    it('keeps the file and reports its path when no default opener is available', async () => {
        const { app, storedFiles } = createApp();
        delete app.openWithDefaultApp;

        await openAndroidPrintDocument(app, 'Print', document.createElement('div'), '');

        expect(storedFiles.has('obsidian-print-output.html')).toBe(true);
        expect(getMockNotices()).toContain(
            'Saved the printable document as "obsidian-print-output.html". Open it in a browser to print.'
        );
    });
});
