import { App, Notice, TFile } from 'obsidian';
import {
    createPortablePrintDocument,
    showPortableImageWarning
} from './portablePrintDocument';

const GENERATED_FILE_MARKER = '<!-- Generated by the Obsidian Print plugin. This file is replaced by the next Android print. -->';
const OUTPUT_FILE_NAME = 'obsidian-print-output.html';
const MAX_OUTPUT_FILE_CANDIDATES = 100;

type AppWithDefaultOpener = App & {
    openWithDefaultApp?: (path: string) => void | Promise<void>;
};

/**
 * Save a portable print document and open it outside Android WebView.
 * Android WebView cannot start the native print dialog from JavaScript.
 */
export async function openAndroidPrintDocument(
    app: App,
    title: string,
    content: HTMLElement,
    cssText: string,
    bodyClasses: string[] = [],
    includeAppClasses = true
): Promise<void> {
    const portableDocument = await createPortablePrintDocument(
        app,
        title,
        content,
        cssText,
        bodyClasses,
        includeAppClasses
    );
    const html = [
        GENERATED_FILE_MARKER,
        portableDocument.html
    ].join('\n');

    let outputFile: TFile;

    try {
        outputFile = await writeGeneratedFile(app, html);
    } catch (error) {
        console.error('Could not save the Android print document:', error);
        new Notice('Could not save the printable document.');
        return;
    }

    showPortableImageWarning(portableDocument.failedImageCount);

    const openWithDefaultApp = (app as AppWithDefaultOpener).openWithDefaultApp;
    if (typeof openWithDefaultApp !== 'function') {
        new Notice(`Saved the printable document as "${outputFile.path}". Open it in a browser to print.`);
        return;
    }

    try {
        await openWithDefaultApp.call(app, outputFile.path);
        new Notice('Opened the printable document in your default browser. Use the browser menu to print.');
    } catch (error) {
        console.error('Could not open the Android print document:', error);
        new Notice(`Could not open the printable document. It was saved as "${outputFile.path}".`);
    }
}

async function writeGeneratedFile(app: App, html: string): Promise<TFile> {
    for (let index = 1; index <= MAX_OUTPUT_FILE_CANDIDATES; index++) {
        const path = getOutputPath(index);
        const existingFile = app.vault.getAbstractFileByPath(path);

        if (!existingFile) {
            return await app.vault.create(path, html);
        }

        if (!(existingFile instanceof TFile)) {
            continue;
        }

        const existingContent = await app.vault.cachedRead(existingFile);
        if (!existingContent.startsWith(GENERATED_FILE_MARKER)) {
            continue;
        }

        await app.vault.process(existingFile, () => html);
        return existingFile;
    }

    throw new Error('No safe output filename is available.');
}

function getOutputPath(index: number): string {
    if (index === 1) {
        return OUTPUT_FILE_NAME;
    }

    return `obsidian-print-output-${index}.html`;
}
