import { App, Notice, TFile, arrayBufferToBase64 } from 'obsidian';
import { createStandalonePrintHtml } from './runtimePrintStyles';
import { syncPrintableCloneState } from './syncPrintableClone';

const GENERATED_FILE_MARKER = '<!-- Generated by the Obsidian Print plugin. This file is replaced by the next Android print. -->';
const OUTPUT_FILE_NAME = 'obsidian-print-output.html';
const SOURCE_PATH_ATTRIBUTE = 'data-obsidian-print-source-path';
const MAX_OUTPUT_FILE_CANDIDATES = 100;

const IMAGE_MIME_TYPES: Record<string, string> = {
    avif: 'image/avif',
    bmp: 'image/bmp',
    gif: 'image/gif',
    ico: 'image/x-icon',
    jpeg: 'image/jpeg',
    jpg: 'image/jpeg',
    png: 'image/png',
    svg: 'image/svg+xml',
    tif: 'image/tiff',
    tiff: 'image/tiff',
    webp: 'image/webp'
};

type AppWithDefaultOpener = App & {
    openWithDefaultApp?: (path: string) => void | Promise<void>;
};

/**
 * Save a portable print document and open it outside Android WebView.
 * Android WebView cannot start the native print dialog from JavaScript.
 */
export async function openAndroidPrintDocument(
    app: App,
    title: string,
    content: HTMLElement,
    cssText: string,
    bodyClasses: string[] = [],
    includeAppClasses = true
): Promise<void> {
    const portableContent = content.cloneNode(true) as HTMLElement;
    syncPrintableCloneState(content, portableContent);
    const failedImageCount = await inlineLocalImages(portableContent, app);
    const html = [
        GENERATED_FILE_MARKER,
        createStandalonePrintHtml(
            portableContent,
            cssText,
            title,
            bodyClasses,
            includeAppClasses
        )
    ].join('\n');

    let outputFile: TFile;

    try {
        outputFile = await writeGeneratedFile(app, html);
    } catch (error) {
        console.error('Could not save the Android print document:', error);
        new Notice('Could not save the printable document.');
        return;
    }

    showImageWarning(failedImageCount);

    const openWithDefaultApp = (app as AppWithDefaultOpener).openWithDefaultApp;
    if (typeof openWithDefaultApp !== 'function') {
        new Notice(`Saved the printable document as "${outputFile.path}". Open it in a browser to print.`);
        return;
    }

    try {
        await openWithDefaultApp.call(app, outputFile.path);
        new Notice('Opened the printable document in your default browser. Use the browser menu to print.');
    } catch (error) {
        console.error('Could not open the Android print document:', error);
        new Notice(`Could not open the printable document. It was saved as "${outputFile.path}".`);
    }
}

async function writeGeneratedFile(app: App, html: string): Promise<TFile> {
    for (let index = 1; index <= MAX_OUTPUT_FILE_CANDIDATES; index++) {
        const path = getOutputPath(index);
        const existingFile = app.vault.getAbstractFileByPath(path);

        if (!existingFile) {
            return await app.vault.create(path, html);
        }

        if (!(existingFile instanceof TFile)) {
            continue;
        }

        const existingContent = await app.vault.cachedRead(existingFile);
        if (!existingContent.startsWith(GENERATED_FILE_MARKER)) {
            continue;
        }

        await app.vault.process(existingFile, () => html);
        return existingFile;
    }

    throw new Error('No safe output filename is available.');
}

function getOutputPath(index: number): string {
    if (index === 1) {
        return OUTPUT_FILE_NAME;
    }

    return `obsidian-print-output-${index}.html`;
}

async function inlineLocalImages(content: HTMLElement, app: App): Promise<number> {
    let failedImageCount = 0;

    for (const image of Array.from(content.querySelectorAll<HTMLImageElement>('img'))) {
        const renderedSource = image.getAttribute('src') ?? '';
        if (isPortableImageSource(renderedSource)) {
            continue;
        }

        const sourceContainer = image.closest<HTMLElement>(`[${SOURCE_PATH_ATTRIBUTE}]`);
        const sourcePath = sourceContainer?.getAttribute(SOURCE_PATH_ATTRIBUTE) ?? '';
        const embedPath = image.closest<HTMLElement>('.internal-embed[src]')?.getAttribute('src');
        const imageFile = resolveImageFile(app, embedPath, sourcePath);
        const mimeType = imageFile ? IMAGE_MIME_TYPES[imageFile.extension.toLowerCase()] : undefined;

        if (!imageFile || !mimeType) {
            failedImageCount++;
            continue;
        }

        try {
            const data = await app.vault.readBinary(imageFile);
            image.src = `data:${mimeType};base64,${arrayBufferToBase64(data)}`;
            image.removeAttribute('srcset');
        } catch (error) {
            failedImageCount++;
        }
    }

    return failedImageCount;
}

function resolveImageFile(app: App, embedPath: string | null | undefined, sourcePath: string): TFile | null {
    if (embedPath && sourcePath) {
        return app.metadataCache.getFirstLinkpathDest(embedPath, sourcePath);
    }

    if (!sourcePath) {
        return null;
    }

    const sourceFile = app.vault.getAbstractFileByPath(sourcePath);
    return sourceFile instanceof TFile ? sourceFile : null;
}

function isPortableImageSource(source: string): boolean {
    return /^(?:data:|https?:|\/\/)/i.test(source);
}

function showImageWarning(failedImageCount: number): void {
    if (failedImageCount === 0) {
        return;
    }

    const imageLabel = failedImageCount === 1 ? 'image' : 'images';
    new Notice(`${failedImageCount} local ${imageLabel} could not be included in the printable document.`);
}
